Fix: Remove email content link plugin - EXO-86448
Prior to this change, the EmailContentLinkPlugin is incompletely implemented just to avoid the exception "[Content Link Plugin email wasn't found] [o.s.b.w.servlet.support.ErrorPageFilter<http-nio-0.0.0.0-8080-exec-2>]
java.lang.IllegalStateException: Content Link Plugin email wasn't found" raised when categorizing email to category. This causes a wrong display of the corresponding inserted option.
After this commit, we will remove the email content link plugin to be reworked correctly later, meanwhile the exception will appear but it will not impact the right execution of add category to content tool.